name: raspilot
version: 0.0.1
summary: Raspilot for SNAP
description: Testing
base: core18
confinement: devmode

architectures:
 - build-on: amd64
   run-on: arm64

parts:
  python:
    plugin: python
    python-version: python3
    source: .
    python-packages:
      - pip
      - pkgconfig
      - setuptools
      - joblib
      - pyzmq
      - wheel
      - pyyaml
      - sklearn
      - h5py
      - cython
      - cffi
      - pandacan
      - pycrypto
      - pycryptodome
      - tensorflow==2.3.0
